export const mockAppData = {
  count: 22,
  acl: {
    query: ['group/nuvla-user'],
    add: ['group/nuvla-user'],
  },
  'resource-type': 'module-collection',
  id: 'module',
  resources: [
    {
      valid: true,
      description:
        '# What is nginx?\n\nNginx (pronounced "engine-x") is an open source reverse proxy server for HTTP, HTTPS, SMTP, POP3, and IMAP protocols, as well as a load balancer, HTTP cache, and a web server (origin server). \n\nThe nginx project started with a strong focus on high concurrency, high performance and low memory usage. \n\nIt is licensed under the 2-clause BSD-like license and it runs on Linux, BSD variants, Mac OS X, Solaris, AIX, HP-UX, as well as on other *nix flavors.',
      path: 'examples/nginx',
      license: {
        url: 'https://opensource.org/licenses/BSD-2-Clause',
        name: 'BSD-2 Clause',
        description: 'The 2-Clause BSD License',
      },
      compatibility: 'swarm',
      updated: '2022-10-10T12:52:09.660Z',
      name: 'Nginx',
      created: '2022-10-10T12:34:15.334Z',
      'parent-path': 'examples',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82',
      id: 'module/96f09292-6aa4-49e1-a5d6-e0fb90fbf787',
      'validation-message': 'Docker-compose valid.',
      'resource-type': 'module',
      acl: {
        'view-meta': ['group/nuvla-user', 'group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        'view-data': ['group/nuvla-user', 'group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        manage: ['group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        'view-acl': ['group/nuvla-user', 'group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        'edit-meta': ['group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        'edit-data': ['group/sixsq-devs', 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82'],
        owners: ['group/nuvla-admin'],
      },
      'logo-url': 'https://www.nginx.com/wp-content/uploads/2018/08/NGINX-logo-rgb-large.png',
      versions: [
        {
          href: 'module-application/2a8201dc-4db2-4700-a837-a1a2975bea4e',
          author: 'lionel@sixsq.com',
          commit: 'no commit message',
        },
      ],
      subtype: 'application',
    },
    {
      valid: true,
      description: 'RabbitMQ configured as MQTT and AMQP broker with management web interface.',
      path: 'examples/rabbitmq',
      compatibility: 'swarm',
      updated: '2022-04-05T15:06:16.863Z',
      name: 'RabbitMQ',
      created: '2022-03-31T15:13:11.828Z',
      'parent-path': 'examples',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82',
      id: 'module/bef3b9e6-3c97-494d-9ca9-b7a3120e70e9',
      'validation-message': 'Docker-compose valid.',
      'resource-type': 'module',
      'logo-url': 'https://sos-ch-gva-2.exo.io/nuvla-images/rabbitmq.svg',
      versions: [
        {
          href: 'module-application/c933dc2c-104d-40ab-82eb-fecaa2c29522',
          author: 'lionel@sixsq.com',
          commit: 'no commit message',
        },
        {
          href: 'module-application/62e70f9e-8c09-421b-9ede-99de215c2077',
          author: 'lionel@sixsq.com',
          commit: 'Fix URLs',
        },
      ],
      subtype: 'application',
    },
    {
      description:
        "# Description\n\nJupyter Notebook deployment with generated access token.\n\nThe application contains ESA's SNAP libraries for EO processing and analysis, and automatically attaches a volume to the host's `/eodata` path, where EO data should automatically be mounted by the underlying cloud provider. If the cloud provider mounts EO data in this path, then you'll be also able to find this data, through the Jupyter Notebook, at `/eodata`.\n\n# Requirements\n\nPlease note that when deploying this app through Nuvla.io, you should already have an existing infrastructure service that meets the following requirements:\n\n - EO data must be mounted on the host at `/eodata`\n - Host must have port range 30000-32767 open for ingress\n - Host must be running with Docker Swarm mode enabled\n\nIf you don't yet have an infrastructure service, then please create one first (see more at https://docs.nuvla.io/nuvla/infrastructures) and then launch this resource on it.\n \n# Notes\n\nPlease **note** that from the Jupyter Notebook, the `/eodata` files are mounted in read-only mode!\n\n",
      path: 'examples/jupytereo-with-snap',
      license: {
        url: 'https://opensource.org/licenses/GPL-3.0',
        name: 'GPL 3',
        description: 'GNU General Public License version 3',
      },
      updated: '2022-02-21T16:12:38.450Z',
      name: 'Jupyter-EO with SNAP ',
      created: '2021-11-26T08:39:07.928Z',
      'parent-path': 'examples',
      'data-accept-content-types': [],
      'updated-by': 'user/ef5cddf8-5d70-4c29-89ff-079ef7f90976',
      'created-by': 'user/ef5cddf8-5d70-4c29-89ff-079ef7f90976',
      id: 'module/7a30359d-71b6-4f7b-b27b-f4a35fea5bc7',
      'resource-type': 'module',
      acl: {
        'edit-data': ['group/nuvla-admin'],
        owners: ['group/sixsq-devs', 'user/ef5cddf8-5d70-4c29-89ff-079ef7f90976'],
        'view-acl': ['group/nuvla-admin', 'group/nuvla-user'],
        delete: ['group/nuvla-admin'],
        'view-meta': ['group/nuvla-admin', 'group/nuvla-user'],
        'edit-acl': ['group/nuvla-admin'],
        'view-data': ['group/nuvla-admin', 'group/nuvla-user'],
        manage: ['group/nuvla-admin'],
        'edit-meta': ['group/nuvla-admin'],
      },
      'logo-url': 'https://i.ibb.co/Twch5jL/Untitled.png',
      versions: [
        {
          href: 'module-component/4f7b3b26-672c-4e73-a555-c66e6b16fdca',
          author: 'super',
          commit: 'make public',
        },
        {
          href: 'module-component/6ed1ce0e-1da0-454a-8243-475339c3c5d0',
          author: 'cris@sixsq.com',
          commit: 'init app',
        },
        {
          href: 'module-component/5b21fec9-c0b3-48df-9fab-a0a44a5a9aae',
          author: 'cris@sixsq.com',
          commit: 'change to http',
          published: false,
        },
      ],
      published: false,
      subtype: 'component',
    },
    {
      valid: false,
      description: 'dataClay master for distributed dataClay architecture',
      path: 'elastictest/dataclay-master',
      license: {
        url: 'https://raw.githubusercontent.com/bsc-dom/dataclay-packaging/develop/LICENSE.txt',
        name: 'BSD 3-Clause "New" or "Revised" License',
      },
      compatibility: 'docker-compose',
      updated: '2022-03-07T10:52:34.003Z',
      name: 'TESTONLY dataClay master ',
      created: '2021-09-14T13:39:56.294Z',
      'parent-path': 'elastictest',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/a0a65e85-9e41-4cf8-ba87-0f8f3e3ebb5c',
      id: 'module/43054b22-b9c8-40fb-b4f2-8c9c18f57558',
      'validation-message':
        'Named volume "1:/dataclay/storage:rw" is used in service "logicmodule" but no declaration was found in the volumes section.\n',
      'resource-type': 'module',
      acl: {
        'edit-data': ['group/nuvla-admin'],
        owners: [
          'group/elastic-bsc',
          'user/7fc6729a-1af3-46b2-b341-77e8470ec5d0',
          'user/958ba98a-f4b4-4924-a389-be9f6afb4bb0',
        ],
        'view-acl': ['group/nuvla-admin', 'group/nuvla-user'],
        delete: ['group/nuvla-admin'],
        'view-meta': ['group/nuvla-admin', 'group/nuvla-user'],
        'edit-acl': ['group/nuvla-admin'],
        'view-data': ['group/nuvla-admin', 'group/nuvla-user'],
        manage: ['group/nuvla-admin'],
        'edit-meta': ['group/nuvla-admin'],
      },
      'logo-url':
        'https://www.bsc.es/sites/default/files/public/styles/bscw2_-_simple_crop_style/public/bscw2/content/software-app/logo/logo_dataclay_web_bsc.jpg',
      versions: [
        {
          href: 'module-application/979fb4df-dc08-4bb9-ac2b-1a024dcc1ea1',
          author: 'github-nuvla:dgasull',
          commit: 'New dev20210615 version',
        },
        {
          href: 'module-application/e34f9db8-2107-4e35-8471-a82aa11472b2',
          author: 'group/elastic-bsc',
          commit: 'personalize initializer dataClay volume path',
        },
      ],
      subtype: 'application',
    },
    {
      valid: false,
      description: 'dataClay standalone app with all needed components (logicmodule, dsjava, dspython, initializer)',
      path: 'elastictest/dataclay-standalone',
      license: {
        url: 'https://raw.githubusercontent.com/bsc-dom/dataclay-packaging/develop/LICENSE.txt',
        name: 'BSD 3-Clause "New" or "Revised" License',
      },
      compatibility: 'docker-compose',
      updated: '2022-03-07T10:52:34.490Z',
      name: 'TESTONLY dataClay standalone',
      created: '2021-09-14T10:01:53.629Z',
      'parent-path': 'elastictest',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/a0a65e85-9e41-4cf8-ba87-0f8f3e3ebb5c',
      id: 'module/5a61f519-0098-4d9c-994e-578f40a3a6eb',
      'validation-message':
        'Named volume "1:/dataclay/storage:rw" is used in service "logicmodule" but no declaration was found in the volumes section.\n',
      'resource-type': 'module',
      acl: {
        'edit-data': ['group/nuvla-admin'],
        owners: [
          'group/elastic-bsc',
          'user/7fc6729a-1af3-46b2-b341-77e8470ec5d0',
          'user/958ba98a-f4b4-4924-a389-be9f6afb4bb0',
          'user/a0a65e85-9e41-4cf8-ba87-0f8f3e3ebb5c',
          'user/e6e71117-91cb-4cf5-bb98-6a56e22f22ea',
        ],
        'view-acl': ['group/nuvla-admin', 'group/nuvla-user'],
        delete: ['group/nuvla-admin'],
        'view-meta': ['group/nuvla-admin', 'group/nuvla-user'],
        'edit-acl': ['group/nuvla-admin'],
        'view-data': ['group/nuvla-admin', 'group/nuvla-user'],
        manage: ['group/nuvla-admin'],
        'edit-meta': ['group/nuvla-admin'],
      },
      'logo-url': 'https://media.giphy.com/media/ED8N0enSGzux3YEDZe/giphy.gif',
      versions: [
        {
          href: 'module-application/5a0c4c2a-055e-47bd-bf72-a0db9bf6577f',
          author: 'github-nuvla:dgasull',
          commit: 'version dev20210615: removing PYPI_URL',
        },
        {
          href: 'module-application/1d708f32-8a43-4225-8bc9-91f5228599cc',
          author: 'group/elastic-bsc',
          commit: 'debug added',
        },
        {
          href: 'module-application/ec31c6fc-feda-40ee-b3cd-e20760df1750',
          author: 'group/elastic-bsc',
          commit: 'debug deleted',
        },
      ],
      subtype: 'application',
    },
    {
      valid: false,
      description: 'dataClay backend for distributed dataClay architecture',
      path: 'elastictest/dataclay-backend',
      compatibility: 'docker-compose',
      updated: '2022-03-07T10:52:33.981Z',
      name: 'TESTONLY dataClay backend',
      created: '2021-09-14T10:01:13.439Z',
      'parent-path': 'elastictest',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/a0a65e85-9e41-4cf8-ba87-0f8f3e3ebb5c',
      id: 'module/803d66a1-1315-4d0d-924f-1134adf7215b',
      'validation-message':
        'Named volume "1:/dataclay/storage:rw" is used in service "dsjava" but no declaration was found in the volumes section.\n',
      'resource-type': 'module',
      acl: {
        'edit-data': ['group/nuvla-admin'],
        owners: [
          'group/elastic-bsc',
          'user/7fc6729a-1af3-46b2-b341-77e8470ec5d0',
          'user/958ba98a-f4b4-4924-a389-be9f6afb4bb0',
        ],
        'view-acl': ['group/nuvla-admin', 'group/nuvla-user'],
        delete: ['group/nuvla-admin'],
        'view-meta': ['group/nuvla-admin', 'group/nuvla-user'],
        'edit-acl': ['group/nuvla-admin'],
        'view-data': ['group/nuvla-admin', 'group/nuvla-user'],
        manage: ['group/nuvla-admin'],
        'edit-meta': ['group/nuvla-admin'],
      },
      'logo-url':
        'https://www.bsc.es/sites/default/files/public/styles/bscw2_-_simple_crop_style/public/bscw2/content/software-app/logo/logo_dataclay_web_bsc.jpg',
      versions: [
        {
          href: 'module-application/6c7f41a8-56f5-44e0-879b-35f4a3060f5b',
          author: 'github-nuvla:dgasull',
          commit: 'no commit message',
        },
      ],
      subtype: 'application',
    },
    {
      valid: true,
      description:
        "# MJPG-Streamer for NuvlaBox\n\nThis application will deploy an mjpg-streamer server on a NuvlaBox. It allow to retreive video stream from an USB camera and expose it as an MJPG stream over HTTP. \n\nBy default, the app is conected to the NuvlaBox's shared network.",
      path: 'lionel/tests/mjpgstreamer-for-nuvlabox',
      compatibility: 'docker-compose',
      updated: '2022-04-05T15:05:19.293Z',
      name: 'MJPG-Streamer for NuvlaBox',
      created: '2021-09-01T04:44:20.110Z',
      'parent-path': 'lionel/tests',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/7644d34d-4c59-47d5-bdde-6d4c3deedb82',
      id: 'module/8fbc737d-3201-493f-90e7-376f8d759d15',
      'validation-message': 'Docker-compose valid.',
      'resource-type': 'module',
      'logo-url': 'https://media.giphy.com/media/JTmtoOQi4eveoiAcoo/giphy.gif',
      versions: [
        {
          href: 'module-application/4ac77b22-f152-4045-b100-98ef1b6cb867',
          author: 'lionel@sixsq.com',
          commit: 'no commit message',
        },
        {
          href: 'module-application/90dc7205-1456-45e5-8344-dc6e66aa1974',
          author: 'lionel@sixsq.com',
          commit: 'minor bugfix',
        },
        {
          href: 'module-application/77cf9f04-ba2b-4547-8a90-d6e12026989d',
          author: 'lionel@sixsq.com',
          commit: 'Remove INTERNAL_PORT',
        },
        {
          href: 'module-application/9f1dea86-833b-4f93-a215-1c31fe07888f',
          author: 'lionel@sixsq.com',
          commit: 'Remove EXTERNAL_PORT',
        },
        {
          href: 'module-application/4d368f96-4751-41bd-bd5e-253e5bb5c005',
          author: 'lionel@sixsq.com',
          commit: 'Add 8881 as external port',
        },
        {
          href: 'module-application/fa5b5773-a71a-42eb-a310-c20096dff4d8',
          author: 'lionel@sixsq.com',
          commit: 'fix stream url',
          published: true,
        },
      ],
      published: true,
      subtype: 'application',
    },
    {
      valid: true,
      description:
        "# NuvlaBox Data Source for Video Devices (MJPEG)\n\nThis application will deploy a data collector, that will automatically consume raw video from a given video peripheral device, compress it, and send the resulting MJPEG binary data to an MQTT broker.\n\nBy default, the app is located at the NuvlaBox's shared network, thus it will make use of the NuvlaBox Data Gateway to publish the MQTT messages.\n\nThe user can then subscribe to the same Data Gateway, at the chosen topic name, to consume the video data.",
      path: 'sixsq/nuvlabox-data-source--video-mjpeg',
      license: {
        url: 'https://opensource.org/licenses/Apache-2.0',
        name: 'Apache 2.0',
        description: 'Apache License, Version 2.0, January 2004',
      },
      compatibility: 'docker-compose',
      updated: '2021-06-01T09:51:08.132Z',
      name: 'NuvlaBox Data Source - Video MJPEG',
      created: '2021-06-01T09:14:42.127Z',
      'parent-path': 'sixsq',
      'data-accept-content-types': [],
      'updated-by': 'group/nuvla-admin',
      'created-by': 'user/ef5cddf8-5d70-4c29-89ff-079ef7f90976',
      id: 'module/33c38bc1-4a6c-4124-9b0e-64ecc3e14770',
      'validation-message': 'Docker-compose valid.',
      'resource-type': 'module',
      acl: {
        'edit-data': ['group/nuvla-admin'],
        owners: ['group/sixsq-devs'],
        'view-acl': ['group/nuvla-admin', 'group/nuvla-user'],
        delete: ['group/nuvla-admin'],
        'view-meta': ['group/nuvla-admin', 'group/nuvla-user'],
        'edit-acl': ['group/nuvla-admin'],
        'view-data': ['group/nuvla-admin', 'group/nuvla-user'],
        manage: ['group/nuvla-admin'],
        'edit-meta': ['group/nuvla-admin'],
      },
      'logo-url': 'https://media.giphy.com/media/JTmtoOQi4eveoiAcoo/giphy.gif',
      versions: [
        {
          href: 'module-application/93287a55-53eb-4264-82f2-7b13d151f92a',
          author: 'group/sixsq-devs',
          commit: 'Initialize application',
        },
        {
          href: 'module-application/0227ca8e-3906-46eb-a1c2-d7aa7b63bb32',
          author: 'group/sixsq-devs',
          commit: 'Fix env var name MQTT_BROKER',
        },
        {
          href: 'module-application/de303aba-d848-49de-9c84-250214a3cfe7',
          author: 'group/sixsq-devs',
          commit: 'Add restart policy',
        },
      ],
      subtype: 'application',
    },
  ],
  operations: [
    {
      rel: 'add',
      href: 'module',
    },
  ],
};
