# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: NuvlaDocs
email: support@sixsq.com
description: Secured edge-to-cloud management platform for near data processing
baseurl: "/" # the subpath of your site, e.g. /blog 
url: "https://docs.nuvla.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sixsq
github_username: nuvla
footer_content: Copyright 2020, SixSq

# Build settings
markdown: kramdown
highlighter: rouge
#remote_theme: pmarsceill/just-the-docs

# Theme configuration.
search_enabled: true
aux_links:
    "Nuvla.io: edge as a Service":
      - "//nuvla.io"
    "Nuvla on GitHub":
      - "//github.com/nuvla"
    "NuvlaBox on GitHub":
      - "//github.com/nuvlabox"


plugins:
  - jekyll-sitemap
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
