name: Screenshotting

on:
  push:
    branches: [issue_87]
  workflow_dispatch:
    inputs:
      USER_NAME_SECRET:
        description: 'Username'
        required: true
      USER_PASSWORD:
        description: 'Password'
        required: true

defaults:
  run:
    working-directory: ./screenshotting

jobs:
  screenshot:
    timeout-minutes: 60
    env:
      USER_NAME_SECRET: ${{ github.event.inputs.USER_NAME_SECRET }}
      USER_PASSWORD: ${{ github.event.inputs.USER_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Testing masking
        run: |
          echo $USER_NAME_SECRET
          echo $USER_PASSWORD
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%Hh_%Mm')"
      - name: Create new branch
        run: git checkout -b screenshot-branch
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - name: Push to origin
        run: git push --set-upstream origin screenshot-branch
